import type { Sku } from './types';

export const BDE_DETAILS = [
  { name: "AKHILA E A", region: "Kerala" },
  { name: "G Kamaraja", region: "Bangalore" },
  { name: "R.Parameshwari", region: "Chennai" },
  { name: "Shusila Devi", region: "Assam" },
  { name: "Swapna Devi Das", region: "Sikkim" },
];

export const ALL_SKUS: Sku[] = [
  // --- PAGE 1 ---
  { id: 'VCFS30', name: 'VITAMIN C FACE SERUM 30 ML', type: 'Natural', category: 'Skin' },
  { id: 'AVG200', name: 'ALOE VERA GEL 200 ML', type: 'Natural', category: 'Body' },
  { id: 'FWSB100', name: 'SKIN BRIGHTENING FACE WASH', type: 'Professional', category: 'Skin' },
  { id: 'HSC70', name: 'CLASSIC HAIR SERUM 70 ML', type: 'Professional', category: 'Hair' },
  { id: 'SHFC300', name: 'HAIR FALL CONTROL SHAMPOO 300 ML', type: 'Professional', category: 'Hair' },
  { id: 'FWAR100', name: 'AGE REVIVAL FACE WASH', type: 'Professional', category: 'Skin' },
  { id: 'MHM125', name: 'HEAVY MOISTURISING MASK 125 ML', type: 'Professional', category: 'Hair' },
  { id: 'SHM300', name: 'HEAVY MOISTURISING SHAMPOO 300 ML', type: 'Professional', category: 'Hair' },
  { id: 'FWOA100', name: 'OIL AWAY FACE WASH', type: 'Professional', category: 'Skin' },
  { id: 'SDC300', name: 'DANDRUFF CONTROL SHAMPOO 300 ML', type: 'Professional', category: 'Hair' },
  { id: 'SBSSS50', name: 'SKIN BRIGHTENING SUNSCREEN SPF 50', type: 'Professional', category: 'Skin' },
  { id: 'MPSS50', name: 'MULTIPROTECTION SUNSCREEN SPF 40', type: 'Professional', category: 'Skin' },
  { id: 'VCLM30', name: 'VITAMIN C LIQUID MOISTURISER 30 ML', type: 'Natural', category: 'Skin' },
  { id: 'VCPFW15', name: 'VITAMIN C POWDER FACE WASH 15 GM', type: 'Natural', category: 'Skin' },
  { id: 'MSB50', name: 'SKIN BRIGHTENING MOISTURISER', type: 'Professional', category: 'Skin' },
  { id: 'TBM125', name: 'TERABOND MASK 125 ML', type: 'Natural', category: 'Hair' },
  { id: 'TBSH200', name: 'TERABOND SHAMPOO 200 ML', type: 'Natural', category: 'Hair' },
  { id: 'HAFS30', name: 'HYALURONIC ACID FACE SERUM 30 ML', type: 'Natural', category: 'Skin' },
  { id: 'MHFC125', name: 'HAIR FALL CONTROL MASK', type: 'Professional', category: 'Hair' },
  { id: 'NCFS30', name: 'NIACINAMIDE FACE SERUM 30 ML', type: 'Natural', category: 'Skin' },
  { id: 'NPFW15', name: 'NEEM POWDER FACE WASH 15 GM', type: 'Natural', category: 'Skin' },
  { id: 'SAFS30', name: 'SALICYLIC ACID FACE SERUM 30 ML', type: 'Natural', category: 'Skin' },
  { id: 'ABFP30', name: 'AHA BHA FACE PEEL 30ML', type: 'Natural', category: 'Skin' },
  { id: 'RPFW15', name: 'ROSE POWDER FACE WASH 15 GM', type: 'Natural', category: 'Skin' },
  { id: 'CFSH200', name: 'CAFFEINE SHAMPOO 200 ML', type: 'Natural', category: 'Hair' },
  { id: 'ARO100', name: 'ARGAN OIL 100 ML', type: 'Natural', category: 'Hair' },
  { id: 'SLBW200', name: 'SALICYLIC & LACTIC ACID BODY WASH 200 ML', type: 'Natural', category: 'Body' },
  { id: 'MAR50', name: 'AGE REVIVAL MOISTURISER', type: 'Professional', category: 'Skin' },
  { id: 'MDC125', name: 'DANDRUFF CONTROL MASK', type: 'Professional', category: 'Hair' },
  { id: 'SALM30', name: 'SALICYLIC ACID LIQUID MOISTURISER 30 ML', type: 'Natural', category: 'Skin' },
  { id: 'SLFW100', name: 'SALICYLIC & LACTIC ACID FACE WASH 100 ML', type: 'Natural', category: 'Skin' },
  { id: 'VCPFW30', name: 'VITAMIN C POWDER FACE WASH 30 GM', type: 'Natural', category: 'Skin' },
  { id: 'RMO100', name: 'ROSEMARY OIL 100 ML', type: 'Natural', category: 'Hair' },
  { id: 'LLSH200', name: 'LACTYLATE SHAMPOO 200 ML', type: 'Natural', category: 'Hair' },
  { id: 'MOA50', name: 'OIL AWAY MOISTURISER', type: 'Professional', category: 'Skin' },
  { id: 'OBOS8', name: 'ONION & BAKUCHIOL OIL SHOTS (8*6 ML)', type: 'Natural', category: 'Hair' },
  { id: 'ARISSS50', name: 'AGE REVIVAL INVISIBLE SUNSCREEN SPF 50', type: 'Professional', category: 'Skin' },
  { id: 'SABL200', name: 'SALICYLIC ACID BODY LOTION 200 ML', type: 'Natural', category: 'Body' },
  { id: 'ONO100', name: 'ONION OIL 100 ML', type: 'Natural', category: 'Hair' },
  { id: 'RPFW30', name: 'ROSE POWDER FACE WASH 30 GM', type: 'Natural', category: 'Skin' },
  { id: 'CCBS200', name: 'COFFEE & COCONUT BODY SCRUB 200 GM', type: 'Natural', category: 'Body' },
  { id: 'LLSS30', name: 'LACTYLATE SCALP SERUM 30 ML', type: 'Natural', category: 'Hair' },
  { id: 'TTSOS8', name: 'TEA TREE & SALICYLIC OIL SHOTS (8*6 ML)', type: 'Natural', category: 'Hair' },
  { id: 'APOS8', name: 'ARGAN & PHYTOLIPID OIL SHOTS (8*6 ML)', type: 'Natural', category: 'Hair' },
  { id: 'ZPSS5', name: 'ZINC POWDER SUNSCREEN 4 GM', type: 'Natural', category: 'Skin' },

  // --- PAGE 2 ---
  { id: 'CCBW200', name: 'COFFEE & COCONUT BODY WASH 200 ML', type: 'Natural', category: 'Body' },
  { id: 'NPFW30', name: 'NEEM POWDER FACE WASH 30 GM', type: 'Natural', category: 'Skin' },
  { id: 'TTO100', name: 'TEA TREE OIL 100 ML', type: 'Natural', category: 'Hair' },
  { id: 'SBISSS50', name: 'SKIN BRIGHTENING INVISIBLE SUNSCREEN SPF 50', type: 'Professional', category: 'Skin' },
  { id: 'CRSS30', name: 'CAFFEINE & MULTIPEPTIDE SCALP SERUM 30 ML', type: 'Natural', category: 'Hair' },
  { id: 'OAISSS50', name: 'OIL AWAY INVISIBLE SUNSCREEN SPF 50', type: 'Professional', category: 'Skin' },
  { id: 'USO30', name: 'ULTIMATE SOOTHING OIL 30 ML', type: 'Professional', category: 'Skin' },
  { id: 'RRGK', name: 'ROSE ROYALE GIFT KIT (1*4)', type: 'Natural', category: 'Gifting' },
  { id: 'LLGK', name: 'LAVENDER LOVE GIFT KIT (1*4)', type: 'Natural', category: 'Gifting' },
  { id: 'PCO200A', name: 'PURE COCONUT OIL', type: 'Natural', category: 'Hair' },
  { id: 'ARSM50', name: 'AGE REVIVAL SERUM MIST 50 ML', type: 'Professional', category: 'Skin' },
  { id: 'SBSM50', name: 'SKIN BRIGHTENING SERUM MIST 50 ML', type: 'Professional', category: 'Skin' },
  { id: 'PRMEO15A', name: 'PURE ROSEMARY ESSENTIAL OIL 15 ML', type: 'Natural', category: 'Hair' },
  { id: 'SSGK', name: 'SAFFRON SWIRL GIFT KIT (1*4)', type: 'Natural', category: 'Gifting' },
  { id: 'MBHO50', name: 'MAHABHRINGRAJ OIL 50 ML', type: 'Natural', category: 'Hair' },
  { id: 'OASM50', name: 'OIL AWAY SERUM MIST 50 ML', type: 'Professional', category: 'Skin' },
  { id: 'CCBL200', name: 'COFEEE & COCONUT BODY LOTION 200 ML', type: 'Natural', category: 'Body' },
  { id: 'ZPSS5_02', name: 'ZINC POWDER SUNSCREEN 4 GM (BEIGE 02)', type: 'Natural', category: 'Skin' },
  { id: 'MFGK', name: 'MINTY FRESH GIFT KIT (1*3)', type: 'Natural', category: 'Gifting' },
  { id: 'CCGK', name: 'COFFEE CONNECTION GIFT KIT (1*4)', type: 'Natural', category: 'Gifting' },
  { id: 'NMSS50', name: 'NATURAL MINERAL SUNSCREEN SPF 50', type: 'Professional', category: 'Skin' },
  { id: 'ZPSS5_03', name: 'ZINC POWDER SUNSCREEN 4 GM (BRONZE 03)', type: 'Natural', category: 'Skin' },
  { id: 'NSLBBS', name: 'NATURE\'S SYMPHONY LUXURY BATHING BARS SET', type: 'Natural', category: 'Body' },
  { id: 'CHPJ10', name: 'CERAMIDE HAIR PERFUME JOY 10 ML', type: 'Professional', category: 'Hair' },
  { id: 'CHPR10', name: 'CERAMIDE HAIR PERFUME RELAX 10 ML', type: 'Professional', category: 'Hair' },
  { id: 'CHPL10', name: 'CERAMIDE HAIR PERFUME LOVE 10 ML', type: 'Professional', category: 'Hair' },
  { id: 'MBHO100', name: 'MAHABHRINGRAJ OIL 100 ML', type: 'Natural', category: 'Hair' },
  { id: 'CHPH10', name: 'CERAMIDE HAIR PERFUME HOPE 10 ML', type: 'Professional', category: 'Hair' },
  { id: 'PSO200', name: 'PURE SESAME OIL', type: 'Natural', category: 'Hair' },
  { id: 'CCBS100', name: 'COFFEE & COCONUT BODY SCRUB 100 GM', type: 'Natural', category: 'Body' },
  { id: 'PAO100A', name: 'PURE ALMOND OIL 100 ML', type: 'Natural', category: 'Hair' },
  { id: 'ARBEFK', name: 'AGE REVIVAL BIO ESSENTIAL FACIAL KIT (1*5)', type: 'Professional', category: 'Skin' },
  { id: 'PDAR15', name: 'AGE REVIVAL POWER DROPS', type: 'Professional', category: 'Skin' },
  { id: 'CPVMS100', name: 'CERAMIDE & PROBIOTICA VEGAN MUCIN SERUM 100 ML', type: 'Natural', category: 'Skin' },
  { id: 'CDHS200', name: 'CERAMIDE HAIR SHIELD 200 ML', type: 'Professional', category: 'Hair' },
  { id: 'CDMS100', name: 'CERAMIDE MAGIC SEAL 100 ML', type: 'Professional', category: 'Hair' },
  { id: 'CDMS200', name: 'CERAMIDE MAGIC SEAL 200 ML', type: 'Professional', category: 'Hair' },
  { id: 'CDM125', name: 'CERAMIDE MASK 125 GM', type: 'Professional', category: 'Hair' },
  { id: 'CDM500', name: 'CERAMIDE MASK 500 GM', type: 'Professional', category: 'Hair' },
  { id: 'CDMT', name: 'CERAMIDE MONOTREATMENT', type: 'Professional', category: 'Hair' },
  { id: 'CDSS200', name: 'Ceramide Scalp Shield 200ml', type: 'Professional', category: 'Hair' },
  { id: 'CDSH1000', name: 'CERAMIDE SHAMPOO 1000 ML', type: 'Professional', category: 'Hair' },
  { id: 'CDSH200', name: 'CERAMIDE SHAMPOO 200 ML', type: 'Professional', category: 'Hair' },
  { id: 'CDSH300', name: 'CERAMIDE SHAMPOO 300 ML', type: 'Professional', category: 'Hair' },
  { id: 'CDS8', name: 'CERAMIDE SHOTS (6*8 ML)', type: 'Professional', category: 'Hair' },

  // --- PAGE 3 ---
  { id: 'HSC200', name: 'Classic Hair serum - 200 ml', type: 'Professional', category: 'Hair' },
  { id: 'CCLB10', name: 'COCONUT LIP BALM 10 GM', type: 'Natural', category: 'Body' },
  { id: 'CCBL100', name: 'COFFEE & COCONUT BODY LOTION 100 ML', type: 'Natural', category: 'Body' },
  { id: 'CCBW100', name: 'COFFEE & COCONUT BODY WASH 100 ML', type: 'Natural', category: 'Body' },
  { id: 'CCHC30', name: 'COFFEE & COCONUT HAND CREME 30 GM', type: 'Natural', category: 'Body' },
  { id: 'CCHL100', name: 'COFFEE & COCONUT HAND LOTION 100 ML', type: 'Natural', category: 'Body' },
  { id: 'CCHW100', name: 'COFFEE & COCONUT HAND WASH 100 ML', type: 'Natural', category: 'Body' },
  { id: 'CCGKC2', name: 'COFFEE CONNECTION GIFT KIT CUSTOMIZE 2', type: 'Natural', category: 'Gifting' },
  { id: 'CCHCK2', name: 'COFFEE CONNECTION HAND CARE KIT', type: 'Natural', category: 'Gifting' },
  { id: 'MDC500', name: 'Dandruff Control Mask - 500 gm', type: 'Professional', category: 'Hair' },
  { id: 'DCHMT', name: 'DANDRUFF CONTROL MONOTREATMENT', type: 'Professional', category: 'Hair' },
  { id: 'DCOS8', name: 'DANDRUFF CONTROL OIL SHOTS (8X6 ML)', type: 'Professional', category: 'Hair' },
  { id: 'DCSSM50', name: 'DANDRUFF CONTROL SCALP SERUM MIST 50 ML', type: 'Professional', category: 'Hair' },
  { id: 'SDC1000', name: 'Dandruff Control Shampoo - 1000ml', type: 'Professional', category: 'Hair' },
  { id: 'DCSFSH300', name: 'DANDRUFF CONTROL SULFATE FREE SHAMPOO', type: 'Professional', category: 'Hair' },
  { id: 'MHFC500', name: 'Hair fall control Mask - 500 gm', type: 'Professional', category: 'Hair' },
  { id: 'HFCOS8', name: 'HAIR FALL CONTROL OIL SHOTS (8X6 ML)', type: 'Professional', category: 'Hair' },
  { id: 'HFCSSM50', name: 'HAIR FALL CONTROL SCALP SERUM MIST 50 ML', type: 'Professional', category: 'Hair' },
  { id: 'SHFC1000', name: 'Hair fall control shampoo 1000ml', type: 'Professional', category: 'Hair' },
  { id: 'HFCSFSH300', name: 'HAIR FALL CONTROL SULFATE FREE SHAMPOO', type: 'Professional', category: 'Hair' },
  { id: 'HFCHMT', name: 'HAIRFALL CONTROL HAIR MONOTREATMENT KIT', type: 'Professional', category: 'Hair' },
  { id: 'MHM500', name: 'Heavy Moisturising Mask - 500 gm', type: 'Professional', category: 'Hair' },
  { id: 'HMHMT', name: 'HEAVY MOISTURISING MONOTREATMENT', type: 'Professional', category: 'Hair' },
  { id: 'HMOS8', name: 'HEAVY MOISTURISING OIL SHOTS (8X6 ML)', type: 'Professional', category: 'Hair' },
  { id: 'SHM1000', name: 'Heavy Moisturising shampoo 1000ml', type: 'Professional', category: 'Hair' },
  { id: 'LCBL100', name: 'LAVENDER & COCONUT BODY LOTION 100 ML', type: 'Natural', category: 'Body' },
  { id: 'LCBL200', name: 'LAVENDER & COCONUT BODY LOTION 200 ML', type: 'Natural', category: 'Body' },
  { id: 'LCBW100', name: 'LAVENDER & COCONUT BODY WASH 100 ML', type: 'Natural', category: 'Body' },
  { id: 'LCBW200', name: 'LAVENDER & COCONUT BODY WASH 200 ML', type: 'Natural', category: 'Body' },
  { id: 'LCHC30', name: 'LAVENDER & COCONUT HAND CREME 30 GM', type: 'Natural', category: 'Body' },
  { id: 'LLGKC3', name: 'LAVENDER LOVE GIFT KIT CUSTOMIZE 3', type: 'Natural', category: 'Gifting' },
  { id: 'MBHO200', name: 'MAHABHRINGRAJ OIL 200 ML', type: 'Natural', category: 'Hair' },
  { id: 'MCBL100', name: 'MINT & COCONUT BODY LOTION 100 ML', type: 'Natural', category: 'Body' },
  { id: 'MCBL200', name: 'MINT & COCONUT BODY LOTION 200 ML', type: 'Natural', category: 'Body' },
  { id: 'MCBW100', name: 'MINT & COCONUT BODY WASH 100 ML', type: 'Natural', category: 'Body' },
  { id: 'MCBW200', name: 'MINT & COCONUT BODY WASH 200 ML', type: 'Natural', category: 'Body' },
  { id: 'MCHC30', name: 'MINT & COCONUT HAND CREME 30 GM', type: 'Natural', category: 'Body' },
  { id: 'ARNPP', name: 'NATURAL PEEL PROGRAMME AGE REVIVAL', type: 'Professional', category: 'Skin' },
  { id: 'OANPP', name: 'NATURAL PEEL PROGRAMME OIL AWAY', type: 'Professional', category: 'Skin' },
  { id: 'SBNPP', name: 'NATURAL PEEL PROGRAMME SKIN BRIGHTENING', type: 'Professional', category: 'Skin' },
  { id: 'NCFW100', name: 'NIACINAMIDE FACE WASH 100 ML', type: 'Natural', category: 'Skin' },
  { id: 'NCISSS50', name: 'NIACINAMIDE INVISIBLE SUNSCREEN SPF 50', type: 'Professional', category: 'Skin' },
  { id: 'OABEFK', name: 'OIL AWAY BIO ESSENTIAL FACIAL KIT', type: 'Professional', category: 'Hair' },
  { id: 'PDOA15', name: 'OIL AWAY POWER DROPS', type: 'Professional', category: 'Skin' },
  { id: 'PCAO200A', name: 'PURE CASTOR OIL', type: 'Natural', category: 'Hair' },
  { id: 'RDCSF30', name: 'ROOT DEEP COMPLETE SCALP FOOD', type: 'Professional', category: 'Hair' },
  { id: 'RDC200', name: 'ROOT DEEP CONDITIONER 200 ML', type: 'Professional', category: 'Hair' },

  // --- PAGE 4 ---
  { id: 'RDHMT', name: 'ROOT DEEP MONOTREATMENT KIT', type: 'Professional', category: 'Hair' },
  { id: 'RDSHY100', name: 'ROOT DEEP SCALP HYDROIL 100 ML', type: 'Professional', category: 'Hair' },
  { id: 'RDSHYK', name: 'ROOT DEEP SCALP HYDROIL KIT', type: 'Professional', category: 'Hair' },
  { id: 'RDSHYSH50', name: 'ROOT DEEP SCALP HYDROIL SHOCK 50 ML', type: 'Professional', category: 'Hair' },
  { id: 'RDSS100', name: 'ROOT DEEP SCALP SERUM 100 ML', type: 'Professional', category: 'Hair' },
  { id: 'RDSSH200', name: 'ROOT DEEP SCALP SHAMPOO 200 ML', type: 'Professional', category: 'Hair' },
  { id: 'RDSS8', name: 'ROOT DEEP SCALP SHOTS (8*6 ML)', type: 'Professional', category: 'Hair' },
  { id: 'RCBL100', name: 'ROSE & COCONUT BODY LOTION 100 ML', type: 'Natural', category: 'Body' },
  { id: 'RCBL200', name: 'ROSE & COCONUT BODY LOTION 200 ML', type: 'Natural', category: 'Body' },
  { id: 'RCBW100', name: 'ROSE & COCONUT BODY WASH 100 ML', type: 'Natural', category: 'Body' },
  { id: 'RCBW200', name: 'ROSE & COCONUT BODY WASH 200 ML', type: 'Natural', category: 'Body' },
  { id: 'RCHC30', name: 'ROSE & COCONUT HAND CREME 30 GM', type: 'Natural', category: 'Body' },
  { id: 'RRGKC3', name: 'ROSE ROYALE GIFT KIT CUSTOMIZE 3', type: 'Natural', category: 'Gifting' },
  { id: 'RMOS8', name: 'ROSEMARY OIL SHOTS (8*6 ML)', type: 'Natural', category: 'Hair' },
  { id: 'SCBL100', name: 'SAFFRON & COCONUT BODY LOTION 100 ML', type: 'Natural', category: 'Body' },
  { id: 'SCBW100', name: 'SAFFRON & COCONUT BODY WASH 100 ML', type: 'Natural', category: 'Body' },
  { id: 'SCBW200', name: 'SAFFRON & COCONUT BODY WASH 200 ML', type: 'Natural', category: 'Body' },
  { id: 'SCHC30', name: 'SAFFRON & COCONUT HAND CREME 30 GM', type: 'Natural', category: 'Body' },
  { id: 'SCHL100', name: 'SAFFRON & COCONUT HAND LOTION 100 ML', type: 'Natural', category: 'Body' },
  { id: 'SCHW100', name: 'SAFFRON & COCONUT HAND WASH 100 ML', type: 'Natural', category: 'Body' },
  { id: 'SCS75', name: 'SAFFRON & COCONUT SOAP 75 GM', type: 'Natural', category: 'Body' },
  { id: 'SSGKC3', name: 'SAFFRON SWIRL GIFT KIT CUSTOMIZE 3', type: 'Natural', category: 'Gifting' },
  { id: 'SSHCK2', name: 'SAFFRON SWIRL HAND CARE KIT (1*2)', type: 'Natural', category: 'Gifting' },
  { id: 'SBBEFK', name: 'SKIN BRIGHTENING BIO ESSENTIAL FACIAL KIT', type: 'Professional', category: 'Skin' },
  { id: 'MSB125', name: 'SKIN BRIGHTENING MOISTURISER 125 ML', type: 'Professional', category: 'Skin' },
  { id: 'PDSB15', name: 'SKIN BRIGHTENING POWER DROPS', type: 'Professional', category: 'Skin' },
];

export const SKU_CATEGORIES = ['All', 'Hair', 'Skin', 'Body', 'Gifting'];