import type { Sku } from './types';

export const BDE_DETAILS = [
  { name: "AKHILA E A", region: "Kerala" },
  { name: "G Kamaraja", region: "Bangalore" },
  { name: "R.Parameshwari", region: "Chennai" },
  { name: "Shusila Devi", region: "Assam" },
  { name: "Swapna Devi Das", region: "Sikkim" },
];

export const ALL_SKUS: Sku[] = [
  // --- PAGE 1 ---
  { id: 'VCFS30', name: 'VITAMIN C FACE SERUM 30 ML', type: 'Natural', category: 'Skin' },
  { id: 'AVG200', name: 'ALOE VERA GEL 200 ML', type: 'Natural', category: 'Body' },
  { id: 'FWSB100', name: 'SKIN BRIGHTENING FACE WASH', type: 'Professional', category: 'Skin' },
  { id: 'HSC70', name: 'CLASSIC HAIR SERUM 70 ML', type: 'Professional', category: 'Hair' },
  { id: 'SHFC300', name: 'HAIR FALL CONTROL SHAMPOO 300 ML', type: 'Professional', category: 'Hair' },
  { id: 'FWAR100', name: 'AGE REVIVAL FACE WASH', type: 'Professional', category: 'Skin' },
  { id: 'MHM125', name: 'HEAVY MOISTURISING MASK 125 ML', type: 'Professional', category: 'Hair' },
  { id: 'SHM300', name: 'HEAVY MOISTURISING SHAMPOO 300 ML', type: 'Professional', category: 'Hair' },
  { id: 'FWOA100', name: 'OIL AWAY FACE WASH', type: 'Professional', category: 'Skin' },
  { id: 'SDC300', name: 'DANDRUFF CONTROL SHAMPOO 300 ML', type: 'Professional', category: 'Hair' },
  { id: 'SBSSS50', name: 'SKIN BRIGHTENING SUNSCREEN SPF 50', type: 'Professional', category: 'Skin' },
  { id: 'MPSS50', name: 'MULTIPROTECTION SUNSCREEN SPF 40', type: 'Professional', category: 'Skin' },
  { id: 'VCLM30', name: 'VITAMIN C LIQUID MOISTURISER 30 ML', type: 'Natural', category: 'Skin' },
  { id: 'VCPFW15', name: 'VITAMIN C POWDER FACE WASH 15 GM', type: 'Natural', category: 'Skin' },
  { id: 'MSB50', name: 'SKIN BRIGHTENING MOISTURISER', type: 'Professional', category: 'Skin' },
  { id: 'TBM125', name: 'TERABOND MASK 125 ML', type: 'Natural', category: 'Hair' },
  { id: 'TBSH200', name: 'TERABOND SHAMPOO 200 ML', type: 'Natural', category: 'Hair' },
  { id: 'HAFS30', name: 'HYALURONIC ACID FACE SERUM 30 ML', type: 'Natural', category: 'Skin' },
  { id: 'MHFC125', name: 'HAIR FALL CONTROL MASK', type: 'Professional', category: 'Hair' },
  { id: 'NCFS30', name: 'NIACINAMIDE FACE SERUM 30 ML', type: 'Natural', category: 'Skin' },
  { id: 'NPFW15', name: 'NEEM POWDER FACE WASH 15 GM', type: 'Natural', category: 'Skin' },
  { id: 'SAFS30', name: 'SALICYLIC ACID FACE SERUM 30 ML', type: 'Natural', category: 'Skin' },
  { id: 'ABFP30', name: 'AHA BHA FACE PEEL 30ML', type: 'Natural', category: 'Skin' },
  { id: 'RPFW15', name: 'ROSE POWDER FACE WASH 15 GM', type: 'Natural', category: 'Skin' },
  { id: 'CFSH200', name: 'CAFFEINE SHAMPOO 200 ML', type: 'Natural', category: 'Hair' },
  { id: 'ARO100', name: 'ARGAN OIL 100 ML', type: 'Natural', category: 'Hair' },
  { id: 'SLBW200', name: 'SALICYLIC & LACTIC ACID BODY WASH 200 ML', type: 'Natural', category: 'Body' },
  { id: 'MAR50', name: 'AGE REVIVAL MOISTURISER', type: 'Professional', category: 'Skin' },
  { id: 'MDC125', name: 'DANDRUFF CONTROL MASK', type: 'Professional', category: 'Hair' },
  { id: 'SALM30', name: 'SALICYLIC ACID LIQUID MOISTURISER 30 ML', type: 'Natural', category: 'Skin' },
  { id: 'SLFW100', name: 'SALICYLIC & LACTIC ACID FACE WASH 100 ML', type: 'Natural', category: 'Skin' },
  { id: 'VCPFW30', name: 'VITAMIN C POWDER FACE WASH 30 GM', type: 'Natural', category: 'Skin' },
  { id: 'RMO100', name: 'ROSEMARY OIL 100 ML', type: 'Natural', category: 'Hair' },
  { id: 'LLSH200', name: 'LACTYLATE SHAMPOO 200 ML', type: 'Natural', category: 'Hair' },
  { id: 'MOA50', name: 'OIL AWAY MOISTURISER', type: 'Professional', category: 'Skin' },
  { id: 'OBOS8', name: 'ONION & BAKUCHIOL OIL SHOTS (8*6 ML)', type: 'Natural', category: 'Hair' },
  { id: 'ARISSS50', name: 'AGE REVIVAL INVISIBLE SUNSCREEN SPF 50', type: 'Professional', category: 'Skin' },
  { id: 'SABL200', name: 'SALICYLIC ACID BODY LOTION 200 ML', type: 'Natural', category: 'Body' },
  { id: 'ONO100', name: 'ONION OIL 100 ML', type: 'Natural', category: 'Hair' },
  { id: 'RPFW30', name: 'ROSE POWDER FACE WASH 30 GM', type: 'Natural', category: 'Skin' },
  { id: 'CCBS200', name: 'COFFEE & COCONUT BODY SCRUB 200 GM', type: 'Natural', category: 'Body' },
  { id: 'LLSS30', name: 'LACTYLATE SCALP SERUM 30 ML', type: 'Natural', category: 'Hair' },
  { id: 'TTSOS8', name: 'TEA TREE & SALICYLIC OIL SHOTS (8*6 ML)', type: 'Natural', category: 'Hair' },
  { id: 'APOS8', name: 'ARGAN & PHYTOLIPID OIL SHOTS (8*6 ML)', type: 'Natural', category: 'Hair' },
  { id: 'ZPSS5', name: 'ZINC POWDER SUNSCREEN 4 GM', type: 'Natural', category: 'Skin' },

  // --- PAGE 2 ---
  { id: 'CCBW200', name: 'COFFEE & COCONUT BODY WASH 200 ML', type: 'Natural', category: 'Body' },
  { id: 'NPFW30', name: 'NEEM POWDER FACE WASH 30 GM', type: 'Natural', category: 'Skin' },
  { id: 'TTO100', name: 'TEA TREE OIL 100 ML', type: 'Natural', category: 'Hair' },
  { id: 'SBISSS50', name: 'SKIN BRIGHTENING INVISIBLE SUNSCREEN SPF 50', type: 'Professional', category: 'Skin' },
  { id: 'CRSS30', name: 'CAFFEINE & MULTIPEPTIDE SCALP SERUM 30 ML', type: 'Natural', category: 'Hair' },
  { id: 'OAISSS50', name: 'OIL AWAY INVISIBLE SUNSCREEN SPF 50', type: 'Professional', category: 'Skin' },
  { id: 'USO30', name: 'ULTIMATE SOOTHING OIL 30 ML', type: 'Professional', category: 'Skin' },
  { id: 'RRGK', name: 'ROSE ROYALE GIFT KIT (1*4)', type: 'Natural', category: 'Gifting' },
  { id: 'LLGK', name: 'LAVENDER LOVE GIFT KIT (1*4)', type: 'Natural', category: 'Gifting' },
  { id: 'PCO200A', name: 'PURE COCONUT OIL', type: 'Natural', category: 'Hair' },
  { id: 'ARSM50', name: 'AGE REVIVAL SERUM MIST 50 ML', type: 'Professional', category: 'Skin' },
  { id: 'SBSM50', name: 'SKIN BRIGHTENING SERUM MIST 50 ML', type: 'Professional', category: 'Skin' },
  { id: 'PRMEO15A', name: 'PURE ROSEMARY ESSENTIAL OIL 15 ML', type: 'Natural', category: 'Hair' },
  { id: 'SSGK', name: 'SAFFRON SWIRL GIFT KIT (1*4)', type: 'Natural', category: 'Gifting' },
  { id: 'MBHO50', name: 'MAHABHRINGRAJ OIL 50 ML', type: 'Natural', category: 'Hair' },
  { id: 'OASM50', name: 'OIL AWAY SERUM MIST 50 ML', type: 'Professional', category: 'Skin' },
  { id: 'CCBL200', name: 'COFEEE & COCONUT BODY LOTION 200 ML', type: 'Natural', category: 'Body' },
  { id: 'ZPSS5_02', name: 'ZINC POWDER SUNSCREEN 4 GM (BEIGE 02)', type: 'Natural', category: 'Skin' },
  { id: 'MFGK', name: 'MINTY FRESH GIFT KIT (1*3)', type: 'Natural', category: 'Gifting' },
  { id: 'CCGK', name: 'COFFEE CONNECTION GIFT KIT (1*4)', type: 'Natural', category: 'Gifting' },
  { id: 'NMSS50', name: 'NATURAL MINERAL SUNSCREEN SPF 50', type: 'Professional', category: 'Skin' },
  { id: 'ZPSS5_03', name: 'ZINC POWDER SUNSCREEN 4 GM (BRONZE 03)', type: 'Natural', category: 'Skin' },
  { id: 'NSLBBS', name: 'NATURE\'S SYMPHONY LUXURY BATHING BARS SET', type: 'Natural', category: 'Body' },
  { id: 'CHPJ10', name: 'CERAMIDE HAIR PERFUME JOY 10 ML', type: 'Professional', category: 'Hair' },
  { id: 'CHPR10', name: 'CERAMIDE HAIR PERFUME RELAX 10 ML', type: 'Professional', category: 'Hair' },
  { id: 'CHPL10', name: 'CERAMIDE HAIR PERFUME LOVE 10 ML', type: 'Professional', category: 'Hair' },
  { id: 'MBHO100', name: 'MAHABHRINGRAJ OIL 100 ML', type: 'Natural', category: 'Hair' },
  { id: 'CHPH10', name: 'CERAMIDE HAIR PERFUME HOPE 10 ML', type: 'Professional', category: 'Hair' },
  { id: 'PSO200', name: 'PURE SESAME OIL', type: 'Natural', category: 'Hair' },
  { id: 'CCBS100', name: 'COFFEE & COCONUT BODY SCRUB 100 GM', type: 'Natural', category: 'Body' },
  { id: 'PAO100A', name: 'PURE ALMOND OIL 100 ML', type: 'Natural', category: 'Hair' },
  { id: 'ARBEFK', name: 'AGE REVIVAL BIO ESSENTIAL FACIAL KIT (1*5)', type: 'Professional', category: 'Skin' },
  { id: 'PDAR15', name: 'AGE REVIVAL POWER DROPS', type: 'Professional', category: 'Skin' },
  { id: 'CPVMS100', name: 'CERAMIDE & PROBIOTICA VEGAN MUCIN SERUM 100 ML', type: 'Natural', category: 'Skin' },
  { id: 'CDHS200', name: 'CERAMIDE HAIR SHIELD 200 ML', type: 'Professional', category: 'Hair' },
  { id: 'CDMS100', name: 'CERAMIDE MAGIC SEAL 100 ML', type: 'Professional', category: 'Hair' },
  { id: 'CDMS200', name: 'CERAMIDE MAGIC SEAL 200 ML', type: 'Professional', category: 'Hair' },
  { id: 'CDM125', name: 'CERAMIDE MASK 125 GM', type: 'Professional', category: 'Hair' },
  { id: 'CDM500', name: 'CERAMIDE MASK 500 GM', type: 'Professional', category: 'Hair' },
  { id: 'CDMT', name: 'CERAMIDE MONOTREATMENT', type: 'Professional', category: 'Hair' },
  { id: 'CDSS200', name: 'Ceramide Scalp Shield 200ml', type: 'Professional', category: 'Hair' },
  { id: 'CDSH1000', name: 'CERAMIDE SHAMPOO 1000 ML', type: 'Professional', category: 'Hair' },
  { id: 'CDSH200', name: 'CERAMIDE SHAMPOO 200 ML', type: 'Professional', category: 'Hair' },
  { id: 'CDSH300', name: 'CERAMIDE SHAMPOO 300 ML', type: 'Professional', category: 'Hair' },
  { id: 'CDS8', name: 'CERAMIDE SHOTS (6*8 ML)', type: 'Professional', category: 'Hair' },

  // --- PAGE 3 ---
  { id: 'HSC200', name: 'Classic Hair serum - 200 ml', type: 'Professional', category: 'Hair' },
  { id: 'CCLB10', name: 'COCONUT LIP BALM 10 GM', type: 'Natural', category: 'Body' },
  { id: 'CCBL100', name: 'COFFEE & COCONUT BODY LOTION 100 ML', type: 'Natural', category: 'Body' },
  { id: 'CCBW100', name: 'COFFEE & COCONUT BODY WASH 100 ML', type: 'Natural', category: 'Body' },
  { id: 'CCHC30', name: 'COFFEE & COCONUT HAND CREME 30 GM', type: 'Natural', category: 'Body' },
  { id: 'CCHL100', name: 'COFFEE & COCONUT HAND LOTION 100 ML', type: 'Natural', category: 'Body' },
  { id: 'CCHW100', name: 'COFFEE & COCONUT HAND WASH 100 ML', type: 'Natural', category: 'Body' },
  { id: 'CCGKC2', name: 'COFFEE CONNECTION GIFT KIT CUSTOMIZE 2', type: 'Natural', category: 'Gifting' },
  { id: 'CCHCK2', name: 'COFFEE CONNECTION HAND CARE KIT', type: 'Natural', category: 'Gifting' },
  { id: 'MDC500', name: 'Dandruff Control Mask - 500 gm', type: 'Professional', category: 'Hair' },
  { id: 'DCHMT', name: 'DANDRUFF CONTROL MONOTREATMENT', type: 'Professional', category: 'Hair' },
  { id: 'DCOS8', name: 'DANDRUFF CONTROL OIL SHOTS (8X6 ML)', type: 'Professional', category: 'Hair' },
  { id: 'DCSSM50', name: 'DANDRUFF CONTROL SCALP SERUM MIST 50 ML', type: 'Professional', category: 'Hair' },
  { id: 'SDC1000', name: 'Dandruff Control Shampoo - 1000ml', type: 'Professional', category: 'Hair' },
  { id: 'DCSFSH300', name: 'DANDRUFF CONTROL SULFATE FREE SHAMPOO', type: 'Professional', category: 'Hair' },
  { id: 'MHFC500', name: 'Hair fall control Mask - 500 gm', type: 'Professional', category: 'Hair' },
  { id: 'HFCOS8', name: 'HAIR FALL CONTROL OIL SHOTS (8X6 ML)', type: 'Professional', category: 'Hair' },
  { id: 'HFCSSM50', name: 'HAIR FALL CONTROL SCALP SERUM MIST 50 ML', type: 'Professional', category: 'Hair' },
  { id: 'SHFC1000', name: 'Hair fall control shampoo 1000ml', type: 'Professional', category: 'Hair' },
  { id: 'HFCSFSH300', name: 'HAIR FALL CONTROL SULFATE FREE SHAMPOO', type: 'Professional', category: 'Hair' },
  { id: 'HFCHMT', name: 'HAIRFALL CONTROL HAIR MONOTREATMENT KIT', type: 'Professional', category: 'Hair' },
  { id: 'MHM500', name: 'Heavy Moisturising Mask - 500 gm', type: 'Professional', category: 'Hair' },
  { id: 'HMHMT', name: 'HEAVY MOISTURISING MONOTREATMENT', type: 'Professional', category: 'Hair' },
  { id: 'HMOS8', name: 'HEAVY MOISTURISING OIL SHOTS (8X6 ML)', type: 'Professional', category: 'Hair' },
  { id: 'SHM1000', name: 'Heavy Moisturising shampoo 1000ml', type: 'Professional', category: 'Hair' },
  { id: 'LCBL100', name: 'LAVENDER & COCONUT BODY LOTION 100 ML', type: 'Natural', category: 'Body' },
  { id: 'LCBL200', name: 'LAVENDER & COCONUT BODY LOTION 200 ML', type: 'Natural', category: 'Body' },
  { id: 'LCBW100', name: 'LAVENDER & COCONUT BODY WASH 100 ML', type: 'Natural', category: 'Body' },
  { id: 'LCBW200', name: 'LAVENDER & COCONUT BODY WASH 200 ML', type: 'Natural', category: 'Body' },
  { id: 'LCHC30', name: 'LAVENDER & COCONUT HAND CREME 30 GM', type: 'Natural', category: 'Body' },
  { id: 'LLGKC3', name: 'LAVENDER LOVE GIFT KIT CUSTOMIZE 3', type: 'Natural', category: 'Gifting' },
  { id: 'MBHO200', name: 'MAHABHRINGRAJ OIL 200 ML', type: 'Natural', category: 'Hair' },
  { id: 'MCBL100', name: 'MINT & COCONUT BODY LOTION 100 ML', type: 'Natural', category: 'Body' },
  { id: 'MCBL200', name: 'MINT & COCONUT BODY LOTION 200 ML', type: 'Natural', category: 'Body' },
  { id: 'MCBW100', name: 'MINT & COCONUT BODY WASH 100 ML', type: 'Natural', category: 'Body' },
  { id: 'MCBW200', name: 'MINT & COCONUT BODY WASH 200 ML', type: 'Natural', category: 'Body' },
  { id: 'MCHC30', name: 'MINT & COCONUT HAND CREME 30 GM', type: 'Natural', category: 'Body' },
  { id: 'ARNPP', name: 'NATURAL PEEL PROGRAMME AGE REVIVAL', type: 'Professional', category: 'Skin' },
  { id: 'OANPP', name: 'NATURAL PEEL PROGRAMME OIL AWAY', type: 'Professional', category: 'Skin' },
  { id: 'SBNPP', name: 'NATURAL PEEL PROGRAMME SKIN BRIGHTENING', type: 'Professional', category: 'Skin' },
  { id: 'NCFW100', name: 'NIACINAMIDE FACE WASH 100 ML', type: 'Natural', category: 'Skin' },
  { id: 'NCISSS50', name: 'NIACINAMIDE INVISIBLE SUNSCREEN SPF 50', type: 'Professional', category: 'Skin' },
  { id: 'OABEFK', name: 'OIL AWAY BIO ESSENTIAL FACIAL KIT', type: 'Professional', category: 'Hair' },
  { id: 'PDOA15', name: 'OIL AWAY POWER DROPS', type: 'Professional', category: 'Skin' },
  { id: 'PCAO200A', name: 'PURE CASTOR OIL', type: 'Natural', category: 'Hair' },
  { id: 'RDCSF30', name: 'ROOT DEEP COMPLETE SCALP FOOD', type: 'Professional', category: 'Hair' },
  { id: 'RDC200', name: 'ROOT DEEP CONDITIONER 200 ML', type: 'Professional', category: 'Hair' },

  // --- PAGE 4 ---
  { id: 'RDHMT', name: 'ROOT DEEP MONOTREATMENT KIT', type: 'Professional', category: 'Hair' },
  { id: 'RDSHY100', name: 'ROOT DEEP SCALP HYDROIL 100 ML', type: 'Professional', category: 'Hair' },
  { id: 'RDSHYK', name: 'ROOT DEEP SCALP HYDROIL KIT', type: 'Professional', category: 'Hair' },
  { id: 'RDSHYSH50', name: 'ROOT DEEP SCALP HYDROIL SHOCK 50 ML', type: 'Professional', category: 'Hair' },
  { id: 'RDSS100', name: 'ROOT DEEP SCALP SERUM 100 ML', type: 'Professional', category: 'Hair' },
  { id: 'RDSSH200', name: 'ROOT DEEP SCALP SHAMPOO 200 ML', type: 'Professional', category: 'Hair' },
  { id: 'RDSS8', name: 'ROOT DEEP SCALP SHOTS (8*6 ML)', type: 'Professional', category: 'Hair' },
  { id: 'RCBL100', name: 'ROSE & COCONUT BODY LOTION 100 ML', type: 'Natural', category: 'Body' },
  { id: 'RCBL200', name: 'ROSE & COCONUT BODY LOTION 200 ML', type: 'Natural', category: 'Body' },
  { id: 'RCBW100', name: 'ROSE & COCONUT BODY WASH 100 ML', type: 'Natural', category: 'Body' },
  { id: 'RCBW200', name: 'ROSE & COCONUT BODY WASH 200 ML', type: 'Natural', category: 'Body' },
  { id: 'RCHC30', name: 'ROSE & COCONUT HAND CREME 30 GM', type: 'Natural', category: 'Body' },
  { id: 'RRGKC3', name: 'ROSE ROYALE GIFT KIT CUSTOMIZE 3', type: 'Natural', category: 'Gifting' },
  { id: 'RMOS8', name: 'ROSEMARY OIL SHOTS (8*6 ML)', type: 'Natural', category: 'Hair' },
  { id: 'SCBL100', name: 'SAFFRON & COCONUT BODY LOTION 100 ML', type: 'Natural', category: 'Body' },
  { id: 'SCBW100', name: 'SAFFRON & COCONUT BODY WASH 100 ML', type: 'Natural', category: 'Body' },
  { id: 'SCBW200', name: 'SAFFRON & COCONUT BODY WASH 200 ML', type: 'Natural', category: 'Body' },
  { id: 'SCHC30', name: 'SAFFRON & COCONUT HAND CREME 30 GM', type: 'Natural', category: 'Body' },
  { id: 'SCHL100', name: 'SAFFRON & COCONUT HAND LOTION 100 ML', type: 'Natural', category: 'Body' },
  { id: 'SCHW100', name: 'SAFFRON & COCONUT HAND WASH 100 ML', type: 'Natural', category: 'Body' },
  { id: 'SCS75', name: 'SAFFRON & COCONUT SOAP 75 GM', type: 'Natural', category: 'Body' },
  { id: 'SSGKC3', name: 'SAFFRON SWIRL GIFT KIT CUSTOMIZE 3', type: 'Natural', category: 'Gifting' },
  { id: 'SSHCK2', name: 'SAFFRON SWIRL HAND CARE KIT (1*2)', type: 'Natural', category: 'Gifting' },
  { id: 'SBBEFK', name: 'SKIN BRIGHTENING BIO ESSENTIAL FACIAL KIT', type: 'Professional', category: 'Skin' },
  { id: 'MSB125', name: 'SKIN BRIGHTENING MOISTURISER 125 ML', type: 'Professional', category: 'Skin' },
  { id: 'PDSB15', name: 'SKIN BRIGHTENING POWER DROPS', type: 'Professional', category: 'Skin' },
];

export const SKU_CATEGORIES = ['All', 'Hair', 'Skin', 'Body', 'Gifting'];

// Master Store List for Auto-Complete
export const MASTER_STORES = [
  { id: "BSRN19368", name: "H&G Comm IV" },
  { id: "BSRN31204", name: "Lulu Daily Fresh Market" },
  { id: "BSRN19504", name: "Mumuso Mantri Mall" },
  { id: "BSRN29868", name: "B&N Puttenahalli" },
  { id: "BSRN31620", name: "B&N M5 E-City Mall" },
  { id: "BSRN32372", name: "Lulu Hyper (Rajaji Nagar)" },
  { id: "BSRN19779", name: "B&N BASAVESHWAR" },
  { id: "BSRN19496", name: "B&N Orion Gateway Mall" },
  { id: "BSRN19539", name: "B&N Koramangala" },
  { id: "BSRN30529", name: "B&N Commercial" },
  { id: "BSRN19527", name: "B&N HSR Layout" },
  { id: "BSRN19950", name: "Madhu Store" },
  { id: "BSRN18260", name: "Nakoda Herbal & Organics" },
  { id: "BSRN19924", name: "Kumar Store (Vaibhav Group)" },
  { id: "BSRN19923", name: "Make Up Biography Indiranagar" },
  { id: "BSRN30362", name: "She Fashion Store" },
  { id: "BSRN31136", name: "Bengaluru Beauty Zone" },
  { id: "BSRN31681", name: "Devatha Gift & Novelties" },
  { id: "BSRN30697", name: "Lucky Beauty Centre" },
  { id: "BSRN30351", name: "Gauri Kangan Store" },
  { id: "BSRN32477", name: "Shree Ramdev Medical" },
  { id: "BSRN20731", name: "Amber Mega Store" },
  { id: "BSRN32755", name: "Anand Medical And Mart" },
  { id: "BSRN31380", name: "Aanjana Novelty Store" },
  { id: "BSRN33185", name: "Shubham Cosmetics" },
  { id: "BSRN23570", name: "H&G- Inorbit Mall" },
  { id: "BSRN23560", name: "H&G-Sujana Mall" },
  { id: "BSRN31638", name: "B&N GSM Mall" },
  { id: "BSRN30927", name: "B&N Nexus Mall" },
  { id: "BSRN31310", name: "B&N Sarath City" },
  { id: "BSRN30937", name: "B&N Lulu Mall" },
  { id: "BSRN32366", name: "B&N Pragathi Nagar" },
  { id: "BSRN33437", name: "B&N Aparna Mall" },
  { id: "BSRN31958", name: "B&N Raichandani Mall" },
  { id: "BSRN34573", name: "B&N DSL Virtue Mall" },
  { id: "BSRN32190", name: "B&N QMart" },
  { id: "BSRN33438", name: "B&N GMR Airport" },
  { id: "BSRN25673", name: "Glory Hub Towlichoki" },
  { id: "BSRN23855", name: "Anil Cosmetics" },
  { id: "BSRN24626", name: "Goutham Enterprises" },
  { id: "BSRN25228", name: "Glory Hub Charminar" },
  { id: "BSRN20148", name: "H&G- Mylapore" },
  { id: "BSRN20534", name: "H&G- Phoenix Mall" },
  { id: "BSRN20092", name: "HG- Pondy Bazar" },
  { id: "BSRN20076", name: "H&G- VR Mall" },
  { id: "BSRN30078", name: "Mumuso VR Mall" },
  { id: "BSRN31175", name: "B&N Nexus Mall" },
  { id: "BSRN31181", name: "B&N VR Mall" },
  { id: "BSRN31685", name: "B&N PALLADIUM" },
  { id: "BSRN20192", name: "Jawala" },
  { id: "BSRN20117", name: "Pixies" },
  { id: "BSRN19563", name: "Beauty 360 Ambattur" },
  { id: "BSRN19550", name: "Beauty 360 Virugambakkam" },
  { id: "BSRN29882", name: "DeGrains & Herbs" },
  { id: "BSRN31141", name: "G. K Cosmetics" },
  { id: "BSRN31137", name: "Mahaveer" },
  { id: "BSRN32123", name: "Bhagavathi Cosmetics" },
  { id: "BSRN19380", name: "H&G Lulu Mall" },
  { id: "BSRN30240", name: "Mumuso Thrissur" },
  { id: "BSRN26665", name: "V-Care Pharma Kakkanad" },
  { id: "BSRN19308", name: "V-Care Pharmacy Aluva" },
  { id: "BSRN19430", name: "Life Phamacy Kollam" },
  { id: "BSRN19509", name: "Life Phamacy Calicut" },
  { id: "BSRN30638", name: "Blsh Lulu Calicut" },
  { id: "BSRN30639", name: "Mumuso Calicut" },
  { id: "BSRN27893", name: "Mumuso Cochin" },
  { id: "BSRN30732", name: "Blsh Kottayam" },
  { id: "BSRN30721", name: "V-Care Pharmacy Perumbavoor" },
  { id: "BSRN31672", name: "B&N Trivandram" },
  { id: "BSRN19552", name: "Dr. Pharmacy" },
  { id: "BSRN27786", name: "WeMart Kakkanad" },
  { id: "BSRN28765", name: "Orchid Palakkad" },
  { id: "BSRN30719", name: "Cochin Beauty" },
  { id: "BSRN30720", name: "Kerala Beauty" },
  { id: "BSRN32782", name: "Orange Collections aluva" },
  { id: "BSRN32959", name: "pearls&petals" },
  { id: "BSRN31908", name: "Midas" },
  { id: "BSRN19808", name: "Mumuso Siliguri Hong kong" },
  { id: "BSRN21679", name: "Mumuso Darjeeling" },
  { id: "BSRN21172", name: "Mumuso Gangtok MG Marg" },
  { id: "BSRN21189", name: "Mumuso Gangtok Vajra" },
  { id: "BSRN20437", name: "Mumuso PBR Siliguri" },
  { id: "BSRN32497", name: "Mumuso west Point" },
  { id: "BSRN21751", name: "Kamals Cosmictics" },
  { id: "BSRN21823", name: "New Bhagawati NX" },
  { id: "BSRN23943", name: "Sreemoti Stores" },
  { id: "BSRN23269", name: "Atmaram Agarwal" },
  { id: "BSRN24749", name: "New Jeevan Jyoti" },
  { id: "BSRN32977", name: "Dhanuka store" },
  { id: "BSRN27114", name: "Rina Stors" },
  { id: "BSRN25280", name: "Subhmangal" },
  { id: "BSRN27965", name: "Manohari Biponi" },
  { id: "BSRN22143", name: "M/S Jyoti" },
  { id: "BSRN30841", name: "Pronay Enterprise" },
  { id: "BSRN30717", name: "R G Enterprise" },
  { id: "BSRN31159", name: "Bhagawati Makeover" },
  { id: "BSRN28704", name: "Kabita Srores" },
  { id: "BSRN30250", name: "Jyoti Cosmetic" },
  { id: "BSRN30905", name: "Nisha Enterprise" },
  { id: "BSRN31207", name: "Molly Imitation Jewellery" },
  { id: "BSRN33308", name: "Smriti" },
  { id: "BSRN32403", name: "Postic" },
  { id: "BSRN31483", name: "Rishi Cosmetic" },
  { id: "BSRN32767", name: "Sharddha" },
  { id: "BSRN20785", name: "Mumuso Elgin" },
  { id: "BSRN22564", name: "Mumuso Park St 1" },
  { id: "BSRN19439", name: "Mumuso Park St 2" },
  { id: "BSRN19482", name: "Mumuso Lake Mall" },
  { id: "BSRN31459", name: "Dabur NewU DCN" },
  { id: "BSRN31639", name: "Dabur NewU Avni" },
  { id: "BSRN32759", name: "Dabur NewU Forum BBSR" },
  { id: "BSRN32652", name: "Dabur NewU DN Regelia BBSR" },
  { id: "BSRN32760", name: "Dabur NewU Ranchi" },
  { id: "BSRN20455", name: "Om Cosmetics 1" },
  { id: "BSRN34240", name: "ADRICAS COSMETICS WORLD" },
  { id: "BSRN31665", name: "Mumuso Itanagar" },
  { id: "BSRN20633", name: "Mumuso Guwahati" },
  { id: "BSRN31183", name: "Mumuso Boingaon" },
  { id: "BSRN20159", name: "Heena Agency" },
  { id: "BSRN21123", name: "Pick Me Fancy Bazar" },
  { id: "BSRN23197", name: "M.M Store" },
  { id: "BSRN23196", name: "Roy Brothers & Sons" },
  { id: "BSRN24727", name: "Sharma Stores" },
  { id: "BSRN28872", name: "Paul Store" },
  { id: "BSRN27535", name: "K.B Store" },
  { id: "BSRN32695", name: "S.K Barua" },
  { id: "BSRN32265", name: "Homoeo Pharmaceutical" },
  { id: "BSRN32635", name: "Beauty Zone" },
  { id: "BSRN32705", name: "Bhagabati Stores" },
  { id: "BSRN33124", name: "Relax Corner" },
  { id: "BSRN33131", name: "M/S Novelty Shopping Center" },
  { id: "BSRN32994", name: "Lansia Store" },
  { id: "BSRN23928", name: "MUMUSO- Bandra" },
  { id: "BSRN30873", name: "Tata Cliq- Seawoods" },
  { id: "BSRN31397", name: "SSL- Saket Delhi" },
  { id: "BSRN32347", name: "SSL- Tapaysa Gurgaon" },
  { id: "BSRN31616", name: "Dabur NewU - Spice Mall" }
];
